version: 0.2

phases:
  install:
    commands:
      - echo "🔧 Starting INSTALL phase..."
      - echo "➡️ Downloading Gitleaks binary..."
      - curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
      - echo "✅ Download complete. Applying execute permission..."
      - chmod +x gitleaks
      - echo "📂 Verifying file exists:"
      - ls -lah gitleaks
      - echo "🔍 Checking version..."
      - ./gitleaks version || echo "❌ Failed to run gitleaks version" && exit 1
      - echo "✅ INSTALL phase complete."

  build:
    commands:
      - echo "🚀 Starting BUILD phase Running Gitleaks scan..."
      - ./gitleaks detect --source . --report-format json --report-path gitleaks-report.json
      - echo "📄 Gitleaks scan complete. Checking for secrets..."
      - |
        if grep -q '"StartLine":' gitleaks-report.json; then
          echo "❌ Secrets detected in the source code!"
          echo "🛑 Failing the build due to secret leakage."
          exit 1
        else
          echo "✅ No secrets found in the code. Build can proceed."
        fi
      - echo "🏁 BUILD phase complete."

artifacts:
  files:
    - gitleaks-report.json




