version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - echo Installing Gitleaks...
      - curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
      - chmod +x gitleaks
      - ls -l gitleaks  # Check file permissions
      - ./gitleaks version  # Confirm it runs
  build:
    commands:
      - echo Running Gitleaks scan...
      - ./gitleaks detect --source . --report-format json --report-path gitleaks-report.json
      - |
        if grep -q '"StartLine":' gitleaks-report.json; then
          echo "Secrets detected! Failing the build."
          exit 1
        else
          echo "No secrets found."
        fi
artifacts:
  files:
    - gitleaks-report.json

