version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
    commands:
      - echo Installing Gitleaks using Go...
      - go install github.com/gitleaks/gitleaks/v8@latest
      - export PATH=$PATH:$(go env GOPATH)/bin
      - gitleaks version  # test run
  build:
    commands:
      - echo Running Gitleaks scan...
      - gitleaks detect --source . --report-format json --report-path gitleaks-report.json
      - |
        if grep -q '"StartLine":' gitleaks-report.json; then
          echo "Secrets detected! Failing the build."
          exit 1
        else
          echo "No secrets found."
        fi
artifacts:
  files:
    - gitleaks-report.json


