# 🟠 AWS Keys
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

# 🟠 Google API Key
GOOGLE_API_KEY = "AIzaSyD-abc123def456ghi789jkl012mno345p"
